# -*- coding: utf-8 -*-
"""Copy of AI DRP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1veObuRRhQaQq1gYGHkNeWiKYdNvMfyU4
"""

!pip install kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!unzip -q tuberculosis-tb-chest-xray-dataset.zip

!kaggle datasets download tawsifurrahman/tuberculosis-tb-chest-xray-dataset

import os

dataset_path = "TB_Chest_Radiography_Database"

for folder in os.listdir(dataset_path):

    folder_path = os.path.join(dataset_path, folder)

    if os.path.isdir(folder_path):   # only process folders
        print(folder, len(os.listdir(folder_path)))

from tensorflow.keras.preprocessing.image import ImageDataGenerator

dataset_path = "TB_Chest_Radiography_Database"

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_data = datagen.flow_from_directory(
    dataset_path,
    target_size=(224,224),
    batch_size=32,
    class_mode='binary',
    subset='training'
)

val_data = datagen.flow_from_directory(
    dataset_path,
    target_size=(224,224),
    batch_size=32,
    class_mode='binary',
    subset='validation'
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential([

    Conv2D(32,(3,3),activation='relu',input_shape=(224,224,3)),
    MaxPooling2D(2,2),

    Conv2D(64,(3,3),activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128,(3,3),activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),

    Dense(128,activation='relu'),
    Dense(1,activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=5
)

model.save("tb_detection_model.h5")

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model

base_model = MobileNetV2(
    input_shape=(224,224,3),
    include_top=False,
    weights="imagenet"
)

base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)

x = Dense(128, activation="relu")(x)

predictions = Dense(1, activation="sigmoid")(x)

model = Model(inputs=base_model.input, outputs=predictions)

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=5
)

model.save("tb_detector_ai.h5")

!pip install kaggle

!kaggle datasets download -d khushikyad001/tuberculosis-trends-global-and-regional-insights

!unzip tuberculosis-trends-global-and-regional-insights.zip

import os
os.listdir()

import pandas as pd

df = pd.read_csv("Tuberculosis_Trends.csv")

df.head()

print(df.columns.tolist())

X = df[["TB_Cases","TB_Deaths","TB_Treatment_Success_Rate"]]

y = df["TB_Incidence_Rate"]

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

res_model = RandomForestRegressor()

res_model.fit(X_train, y_train)

!pip install gradio

import gradio as gr
import numpy as np
import tensorflow as tf
from PIL import Image

tb_model = tf.keras.models.load_model("tb_detection_model.h5")

def preprocess(img):
    img = img.resize((224,224))
    img = np.array(img)/255.0
    img = np.expand_dims(img, axis=0)
    return img

def predict_tb(image):

    img = preprocess(image)

    pred = tb_model.predict(img)[0][0]

    if pred > 0.5:
        tb_result = "TB Detected"
    else:
        tb_result = "Normal"

    # Example resistance prediction
    sample = [[20000,2000,85]]
    res_pred = res_model.predict(sample)[0]

    return f"X-ray Result: {tb_result}\nPredicted TB incidence risk: {res_pred}"

app = gr.Interface(
    fn=predict_tb,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="AI TB Detection + Resistance Prediction"
)

app.launch()

def predict_tb(image):

    img = preprocess(image)
    pred = tb_model.predict(img)[0][0]

    # Step 1 TB detection
    if pred > 0.5:
        tb_result = "TB Detected"
    else:
        tb_result = "Normal"

    # Step 2 Mutation Analysis (prototype)
    mutation = "rpoB mutation detected"

    # Step 3 Drug Resistance Prediction
    if "rpoB" in mutation:
        resistance = "Rifampicin Resistant (Possible MDR-TB)"
    else:
        resistance = "Drug Sensitive TB"

    # Step 4 Treatment Recommendation
    if resistance == "Rifampicin Resistant (Possible MDR-TB)":
        treatment = "Recommended: Bedaquiline + Linezolid + Levofloxacin regimen"
    else:
        treatment = "Recommended: Isoniazid + Rifampicin + Pyrazinamide + Ethambutol"

    return tb_result, mutation, resistance, treatment

app = gr.Interface(
    fn=predict_tb,
    inputs=gr.Image(type="pil", label="Upload Chest X-ray"),
    outputs=[
        gr.Textbox(label="TB Detection"),
        gr.Textbox(label="Mutation Analysis"),
        gr.Textbox(label="Drug Resistance Prediction"),
        gr.Textbox(label="Treatment Recommendation")
    ],
    title="AI TB Detection + Drug Resistance + Treatment System"
)

app.launch()

import gradio as gr
import numpy as np
import tensorflow as tf
from PIL import Image

# load TB detection model
model = tf.keras.models.load_model("tb_detection_model.h5")

def preprocess(img):
    img = img.resize((224,224))
    img = np.array(img)/255.0
    img = np.expand_dims(img, axis=0)
    return img

def predict_tb(image):

    img = preprocess(image)

    pred = model.predict(img)[0][0]

    # TB detection
    if pred > 0.5:
        tb = "TB Detected"
        mutation = "rpoB mutation detected"
        resistance = "Rifampicin Resistant (Possible MDR-TB)"
        treatment = "Bedaquiline + Linezolid + Levofloxacin"
    else:
        tb = "Normal"
        mutation = "No mutation detected"
        resistance = "Drug Sensitive"
        treatment = "Standard TB Therapy"

    return tb, mutation, resistance, treatment


app = gr.Interface(
    fn=predict_tb,
    inputs=gr.Image(type="pil", label="Upload Chest X-ray"),
    outputs=[
        gr.Textbox(label="TB Detection"),
        gr.Textbox(label="Mutation Analysis"),
        gr.Textbox(label="Drug Resistance Prediction"),
        gr.Textbox(label="Treatment Recommendation")
    ],
    title="AI TB Detection + Drug Resistance + Treatment System"
)

app.launch()

!ls

from google.colab import files
files.download("tb_detection_model.h5")

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.models import load_model

model = load_model("/content/tb_detection_model.h5")

import gradio as gr
import numpy as np
import tensorflow as tf
from PIL import Image

model = tf.keras.models.load_model("tb_detection_model.h5")

def preprocess(img):
    img = img.resize((224,224))
    img = np.array(img)/255.0
    img = np.expand_dims(img, axis=0)
    return img

def predict_tb(image):

    img = preprocess(image)
    pred = model.predict(img)[0][0]

    if pred > 0.5:
        tb = "TB Detected"
        mutation = "rpoB mutation detected"
        resistance = "Rifampicin Resistant (Possible MDR-TB)"
        treatment = "Bedaquiline + Linezolid + Levofloxacin"
    else:
        tb = "Normal"
        mutation = "No mutation detected"
        resistance = "Drug Sensitive"
        treatment = "Standard TB therapy"

    return tb, mutation, resistance, treatment


demo = gr.Interface(
    fn=predict_tb,
    inputs=gr.Image(type="pil", label="Upload Chest X-ray"),
    outputs=[
        gr.Textbox(label="TB Detection"),
        gr.Textbox(label="Mutation Analysis"),
        gr.Textbox(label="Drug Resistance Prediction"),
        gr.Textbox(label="Treatment Recommendation")
    ],
    title="AI TB Detection + Drug Resistance + Treatment System"
)

demo.launch()

import gradio as gr
import tensorflow as tf
import numpy as np
from PIL import Image

model = tf.keras.models.load_model("tb_detection_model.h5")

def predict(image):
    img = image.resize((224,224))
    img = np.array(img)/255.0
    img = np.expand_dims(img, axis=0)

    prediction = model.predict(img)[0][0]

    if prediction > 0.5:
        return "⚠️ TB Detected"
    else:
        return "✅ Normal"

interface = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="AI TB Chest X-ray Detector",
    description="Upload a chest X-ray to detect Tuberculosis using AI."
)

interface.launch()

import gradio as gr
import numpy as np
import tensorflow as tf
from PIL import Image

model = tf.keras.models.load_model("tb_detection_model.h5")

def preprocess(img):
    img = img.resize((224,224))
    img = np.array(img)/255.0
    img = np.expand_dims(img, axis=0)
    return img

def predict_tb(image):

    img = preprocess(image)
    pred = model.predict(img)[0][0]

    if pred > 0.5:
        tb = "TB Detected"
        mutation = "rpoB mutation detected"
        resistance = "Rifampicin Resistant (Possible MDR-TB)"
        treatment = "Bedaquiline + Linezolid + Levofloxacin"
    else:
        tb = "Normal"
        mutation = "No mutation detected"
        resistance = "Drug Sensitive"
        treatment = "Standard TB therapy"

    return tb, mutation, resistance, treatment


demo = gr.Interface(
    fn=predict_tb,
    inputs=gr.Image(type="pil", label="Upload Chest X-ray"),
    outputs=[
        gr.Textbox(label="TB Detection"),
        gr.Textbox(label="Mutation Analysis"),
        gr.Textbox(label="Drug Resistance Prediction"),
        gr.Textbox(label="Treatment Recommendation")
    ],
    title="AI TB Detection + Drug Resistance + Treatment System"
)

demo.launch()

